### ISSUE TITLE
Why is every timezone a separate type?

### ISSUE THREAD

**Issue by tiffany352** [djzin/chrono-tz#1]
This makes it so that you can't choose the timezone dynamically based on user input. Why do this? Why isn't an enum over all of them at least provided? Having it like this makes the library unusable for me, and probably many other prospective users.

**Comment by djzin** [comment]
You are right; this was a kind of poor design decision. I rewrote it (& bumped to version 0.2) to use an enum instead. It even implements FromStr so you can convert directly from a string like "Europe/Berlin" to a Tz object.

**Comment by djzin** [comment]
Miraculously, none of the tests failed when I changed it, so your code may very well "just work" even with the changes I made.
