### ISSUE TITLE
Compilation on Windows

### ISSUE THREAD

**Issue by tl8roy** [djzin/chrono-tz#3]
When I try to use chrono-tz on Windows I get the following error:
```
   Compiling datetime v0.4.4
error[E0432]: unresolved import `system::sys_time`
  --> C:\Users\TWB\.cargo\registry\src\github.com-1ecc6299db9ec823\datetime-0.4.4\src\cal\datetime.rs:15:5
   |
15 | use system::sys_time;
   |     ^^^^^^^^^^^^^^^^ no `sys_time` in `system`

error[E0432]: unresolved import `system::sys_time`
 --> C:\Users\TWB\.cargo\registry\src\github.com-1ecc6299db9ec823\datetime-0.4.4\src\instant.rs:6:5
  |
6 | use system::sys_time;
  |     ^^^^^^^^^^^^^^^^ no `sys_time` in `system`

error: aborting due to 2 previous errors

error: Could not compile `datetime`.
```

Investigation on the #rust-beginners channel revealed:

> <@mbrubeck> Indeed, it seems to be missing that function on Windows: https://docs.rs/crate/datetime/0.4.4/source/src/system.rs
> <@mbrubeck> There's one for macOS+iOS, and one for everything except (macOS, iOS, Windows).
> <tl8> right, so what should I do to get it to build?
> <@mbrubeck> It looks like it would need a non-trivial patch to implement sys_time on Windows, though I think you could use https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/time.rs for example code if you want to do that...
> <@mbrubeck> Alternately you could try to patch https://github.com/rust-datetime/zoneinfo-compiled to work with types from std::time or chrono, instead of the datetime crate

**Comment by djzin** [comment]
Thanks for the heads up; it is indeed unfortunate that chrono-tz has this dependency. I'll see if there's a workaround from my end

**Comment by tl8roy** [comment]
I have implemented the missing function in https://github.com/rust-datetime/datetime/pull/16. If it gets approved, I will create a new Pull Request for https://github.com/rust-datetime/zoneinfo-parse and so on.

**Comment by djzin** [comment]
should be fixed by https://github.com/djzin/chrono-tz/commit/bc84a95296c99b23717e53175959d16583423358

but I haven't actually tested it on windows yet ;)

**Comment by djzin** [comment]
tested on windows - ran cargo test and all tests passed
