### ISSUE TITLE
Won't compile with newest `chrono` ver 0.3.*

### ISSUE THREAD

**Issue by jjuraszek** [djzin/chrono-tz#4]
it would be nice for this project to keep up. do you accept PRs?

**Comment by djzin** [comment]
Just saw the post announcing v 0.3, planning on working on this over the weekend - but yes would accept a PR if someone did it for me :)

**Comment by djzin** [comment]
closed by https://github.com/djzin/chrono-tz/commit/9e3c7188d19a7d225fe7e7c754b3b59671d781f5
