### ISSUE TITLE
Human readable names of the time-zones.

### ISSUE THREAD

**Issue by musically-ut** [djzin/chrono-tz#6]
Printing the TimeZone in debug mode (i.e. using `{:?}` formatter) shows a correct name of the zone but that does not seem like a kosher way of arriving at the names.

I couldn't find another way. Since the `Tz` is an `enum`, it cannot provide an attribute like `.name` (re: #1). Also, providing a `.to_string()` (i.e. implementing a `Display` trait), is tricky because a time-zone can have several names depending on the context, e.g. both `Asia/Kolkata` and `IST` can be seen as _expected_ outputs of `.to_string()`.

Perhaps the `Debug` implementation can be moved to a function `get_name` which returns a `String` and then implementation of `Debug` could be:

```
impl Debug for Tz {
    fn fmt(&self, f: &mut Formatter) -> Result<(), Error> {
        write!(f, "{}", get_name(self))
    }
}
```

What do you think?

**Comment by djzin** [comment]
Hm, yes this seems like something that could be provided
Also relevant are the 'offset' names like 'CET' that get printed with datetimes but aren't publicly accessible

**Comment by musically-ut** [comment]
Sounds like a good idea. 

However, don't the abbreviations change depending on DST, e.g. CDST and CDT?
